apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-autogen-team
  labels:
    app: fastapi-autogen-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-autogen-team
  template:
    metadata:
      labels:
        app: fastapi-autogen-team
    spec:
      containers:
        - name: fastapi-autogen-team
          image: lgcorzo/fastapi-autogen-team:v1.1.0
          ports:
            - containerPort: 4100
          envFrom:
            - secretRef:
                name: fastapi-autogen-secrets
          env:
            - name: DEFAULT_OTEL_ENDPOINT
              value: "http://opentelemetry-collector.monitoring.svc.cluster.local:4318/v1"
            - name: DEFAULT_HOST
              value: "0.0.0.0"
